import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import "./../../globals.css";
import Link from "next/link";
import WhatsappChat from "../components/WhatsappChat";
import MobileMenu from "../components/MobileMenu";
import Menu from "../components/Menu";
import { ThemeProvider } from '../components/ThemeProvider';

// 1. Initialize custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Define static metadata for SEO
export const metadata: Metadata = {
  title: "Zikri Aulia | Web Developer", // Added a professional title
  description: "Portfolio of Zikri Aulia, generated by Next.js and Sanity CMS.",
};

/**
 * Global Root Layout
 * * This Server Component wraps every page in the application.
 * * It injects global providers (Themes & Translations) into the component tree.
 */
export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Extract the locale from the URL segment
  const resolvedParams = await params;
  const currentLocale = resolvedParams.locale;

  // Fetch the dictionary for the current language
  const messages = await getMessages();

  return (
    <html lang={currentLocale} className="scroll-smooth" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* THEME PROVIDER: Handles the dark/light mode CSS class switching */}
        <ThemeProvider>
          
          {/* TRANSLATION PROVIDER: A single global wrapper for all dictionary lookups */}
          <NextIntlClientProvider messages={messages} locale={currentLocale}>
            
            {/* NAVIGATION BAR */}
            {/* Note: bg-background automatically handles dark mode via CSS variables! */}
            <nav className="fixed w-full px-2 py-2 z-10 bg-background flex items-center justify-between shadow-sm">
              <Link
                href={`/${currentLocale}`}
                className="font-bold rounded-full bg-black text-white dark:bg-white dark:text-black py-1 pr-2 text-center transition-colors"
              >
                <span className="p-1 mr-2 rounded-full bg-black text-white outline outline-white dark:bg-white dark:text-black dark:outline-black outline-4">
                  ZA
                </span> 
                Portfolio
              </Link>
              
              <MobileMenu />
              <Menu />
            </nav>

            {/* MAIN CONTENT AREA */}
            {/* Fixed the Tailwind typo: changed w-5xl to max-w-5xl */}
            <main className="px-2 lg:max-w-5xl mx-auto">
              {children}            
              <WhatsappChat />
            </main>

            {/* FOOTER */}
            <footer className="text-center bg-black text-white dark:bg-white dark:text-black p-2 mt-auto">
              <p>
                Designed & Built by Zikri Aulia &copy; {new Date().getFullYear()}
              </p>
            </footer>

          </NextIntlClientProvider>
          
        </ThemeProvider>
      </body>
    </html>
  );
}